### ISSUE TITLE
axis-aligned bounding boxes

### ISSUE THREAD

**Issue by kyelok** [scenenn/scenenn#14]
Thanks for sharing this awesome dataset!

The paper mentioned that object bounding boxes are annotated in two ways: oriented bounding boxes and axis-aligned bounding boxes. 

I could find the oriented bounding boxes in the xml (under obbox) but can't find the axis-aligned bounding box labels. Are these available somewhere? If not, do you mind sharing them as well?

**Comment by songuke** [comment]
Dear Kyel,

In the original release the aabb box is not included in the XML. You can
parse the ply file to get the instances, and recompute the AABB from the
instance.

http://103.24.77.34:8080/scenenn/contrib/nyu_class/ This link is an
unofficial release that includes the aabb field for a subset of scenes.


2020年6月17日(水) 10:25 Kyel Ok <notifications@github.com>:

**Comment by kyelok** [comment]
Perfect. Thanks, Binh-Son!
