### ISSUE TITLE
Can not access the dataset source page

### ISSUE THREAD

**Issue by chihong0522** [scenenn/scenenn#17]
Got 500 server side error whenever I download any file from your server. The response is `Error: EMFILE: too many open files, open 'D:\public\scenenn\home\index.html'`. Plz Help!

**Comment by DoctorXK** [comment]
Hello, 

I would like to ask how did you download the data from the server without using the [download script](https://github.com/hkust-vgd/scenenn/blob/master/download/scenenn_download.py) the author provided?
