### ISSUE TITLE
Download link and download method

### ISSUE THREAD

**Issue by glennliu** [scenenn/scenenn#18]
Hi @songuke 

I tried several methods in downloading the RGBD images but all failed. 

1. I used the latest link [http://103.24.77.34/scenenn/](link) you provided. It can be opened but I cannot find the ".oni" files (raw RGBD and intrinsics) in it.
And when I tried to download it with ```wget -r -np http://103.24.77.34/scenenn```, only the ```index.html``` files are downloaded.

2. For the python download scripts you provided, since the earliest google drive link is expired, I think the script cannot be used either. 

Can you kindly help me with it.

Thanks
Glen

**Comment by sonhua** [comment]
Hi Glen, 

For ONI file you can find them here: http://103.24.77.34/scenenn/main/oni/

Thanks.

**Comment by glennliu** [comment]
> Hi Glen,
> 
> For ONI file you can find them here: http://103.24.77.34/scenenn/main/oni/
> 
> Thanks.

@sonhua Thanks for the quick reply.

What kind of download tool do you use? I can't download it with ```wget```. And there isn't download option on the browser.

Thanks

**Comment by glennliu** [comment]
Thanks @sonhua 

It's been solved. The link can frequently be unavailable. Just try more times at different periods, it can be downloaded successfully.

**Comment by glennliu** [comment]
solved

**Comment by DoctorXK** [comment]
> Thanks @sonhua
> 
> It's been solved. The link can frequently be unavailable. Just try more times at different periods, it can be downloaded successfully.

Hello,

Could you please tell me how did you download the whole dataset in [download link](http://hkust-vgd.ust.hk/scenenn/main/)? Since the GoogleDrive Link the author provided is broken, the python download script was unable to work too.
